# -*- coding: utf-8 -*-
"""Codenrock_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nwB41nE63NWk6lWEMia8BrpkWpMJh1bt
"""

!pip -q install scikit-learn pandas numpy

import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline

DATA_DIR = "/content/init_data"

train = pd.read_csv(f"{DATA_DIR}/train_chat.csv")
test  = pd.read_csv(f"{DATA_DIR}/test_chat.csv")
sample = pd.read_csv(f"{DATA_DIR}/sample_submission_chat.csv")

train.head()

def build_text(df):
    return (
        df["text"].fillna("") +
        " <DAY_" + df["day"].astype(str) + ">" +
        " <HOUR_" + df["hour"].astype(str) + ">"
    )

train["full_text"] = build_text(train)
test["full_text"]  = build_text(test)

tfidf = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.9,
    analyzer="word",
    sublinear_tf=True
)

clf = LogisticRegression(
    C=6,
    max_iter=3000,
    class_weight="balanced",
    n_jobs=-1
)

pipe = Pipeline([
    ("tfidf", tfidf),
    ("clf", clf)
])

X = train["full_text"]
y = train["topic"]

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = []

for fold, (tr_idx, val_idx) in enumerate(skf.split(X, y), 1):
    X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]

    pipe.fit(X_tr, y_tr)
    preds = pipe.predict(X_val)

    f1 = f1_score(y_val, preds, average="macro")
    scores.append(f1)

    print(f"Fold {fold}: Macro-F1 = {f1:.4f}")

print("Mean Macro-F1:", np.mean(scores))

pipe.fit(train["full_text"], train["topic"])

test_preds = pipe.predict(test["full_text"])

submission = pd.DataFrame({
    "message_id": test["message_id"],
    "topic": test_preds
})

submission.to_csv("submission.csv", index=False)
submission.head()